//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryOfPortall.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBook
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblBook()
        {
            this.TblReserveds = new HashSet<TblReserved>();
            this.TblRequests = new HashSet<TblRequest>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> DateOfEntry { get; set; }
        public Nullable<byte> CategoryID { get; set; }
        public Nullable<byte> RegionID { get; set; }
        public string Code { get; set; }
        public string BookName { get; set; }
        public string Author { get; set; }
        public string PublishingHouse { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual TblCategory TblCategory { get; set; }
        public virtual TblRegion TblRegion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblReserved> TblReserveds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblRequest> TblRequests { get; set; }
    }
}
