
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LibraryOfPortall.Models.EntityFramework
{

using System;
    using System.Collections.Generic;
    
public partial class TblRegion
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TblRegion()
    {

        this.TblBooks = new HashSet<TblBook>();

        this.TblUsers = new HashSet<TblUser>();

    }


    public byte ID { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public Nullable<byte> CityID { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TblBook> TblBooks { get; set; }

    public virtual TblCity TblCity { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TblUser> TblUsers { get; set; }

}

}
