
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LibraryOfPortall.Models.EntityFramework
{

using System;
    using System.Collections.Generic;
    
public partial class TblUnregisteredReserve
{

    public int ID { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }

    public string RegistryNo { get; set; }

    public Nullable<int> BookID { get; set; }

    public Nullable<bool> Status { get; set; }



    public virtual TblBook TblBook { get; set; }

}

}
