//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryOfPortall.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblUser()
        {
            this.TblReserveds = new HashSet<TblReserved>();
            this.TblRequests = new HashSet<TblRequest>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Tc { get; set; }
        public string RegistryNo { get; set; }
        public Nullable<byte> RegionID { get; set; }
        public Nullable<byte> DepartmentID { get; set; }
        public string PhoneNo { get; set; }
        public string Password { get; set; }
        public Nullable<byte> AuthorityID { get; set; }
    
        public virtual TblAuthority TblAuthority { get; set; }
        public virtual TblDepartment TblDepartment { get; set; }
        public virtual TblRegion TblRegion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblReserved> TblReserveds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblRequest> TblRequests { get; set; }
    }
}
